# Generated by Django 6.0.2 on 2026-02-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='エージェント名', max_length=100, unique=True)),
                ('command', models.CharField(help_text='実行コマンド（例: claude --dangerously-skip-permissions -p）', max_length=500)),
                ('system_message', models.TextField(blank=True, help_text='システムメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=255)),
                ('workdir', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.JSONField(default=list, help_text='参照用ファイルリスト')),
                ('edit_files', models.JSONField(default=list, help_text='編集対象ファイルリスト')),
                ('prompt', models.TextField(help_text='タスク内容')),
                ('context', models.TextField(blank=True, help_text='動的に注入するコンテキスト')),
                ('completed_at', models.BooleanField(default=False)),
                ('output', models.TextField(blank=True, help_text='実行結果', null=True)),
                ('validation_command', models.CharField(blank=True, help_text='完了判断用コマンド', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='使用するエージェント', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='todo.agent')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todo.todolist')),
            ],
        ),
    ]
