# Generated by Django 6.0.2 on 2026-02-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="files",
            new_name="ref_files",
        ),
    ]
