# Generated by Django 6.0.2 on 2026-02-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_files_todo_ref_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="command",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="repository",
        ),
        migrations.AddField(
            model_name="todo",
            name="branch_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
