# Generated by Django 6.0.2 on 2026-02-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_agent_command_remove_todolist_repository_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='waiting', help_text='タスクのステータス', max_length=20),
        ),
    ]
