# Generated by Django 6.0.2 on 2026-02-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_remove_todo_completed_at_todo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="timeout",
            field=models.IntegerField(default=3600, help_text="タイムアウト秒数"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("timeout", "Timeout"),
                    ("error", "Error"),
                ],
                default="waiting",
                help_text="タスクのステータス",
                max_length=20,
            ),
        ),
    ]
