# Generated by Django 6.0.2 on 2026-02-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_todo_timeout_alter_todo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="auto_stash",
            field=models.BooleanField(default=True, help_text="自動スタッシュ"),
        ),
    ]
