# Generated by Django 6.0.2 on 2026-02-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_todo_auto_stash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="拡張機能名", max_length=100, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="stdio", help_text="拡張機能タイプ", max_length=20
                    ),
                ),
                ("cmd", models.CharField(help_text="実行コマンド", max_length=500)),
                (
                    "args",
                    models.JSONField(default=list, help_text="コマンド引数リスト"),
                ),
                ("envs", models.JSONField(default=dict, help_text="環境変数マップ")),
                (
                    "timeout",
                    models.IntegerField(default=300, help_text="タイムアウト秒数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="system_prompt",
            field=models.TextField(blank=True, help_text="システムプロンプト"),
        ),
        migrations.AddField(
            model_name="todolist",
            name="name",
            field=models.CharField(default="", help_text="リスト名", max_length=255),
        ),
        migrations.AlterField(
            model_name="todo",
            name="edit_files",
            field=models.JSONField(
                blank=True, default=list, help_text="編集対象ファイルリスト"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="ref_files",
            field=models.JSONField(
                blank=True, default=list, help_text="参照用ファイルリスト"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="extensions",
            field=models.ManyToManyField(
                blank=True,
                help_text="使用する拡張機能",
                related_name="agents",
                to="todo.extension",
            ),
        ),
    ]
