# Generated by Django 6.0.2 on 2026-02-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_extension_todo_system_prompt_todolist_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="title",
            field=models.CharField(
                default="", help_text="タスクのタイトル", max_length=255
            ),
        ),
    ]
