# Generated by Django 6.0.2 on 2026-02-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='keep_branch',
            field=models.BooleanField(default=False, help_text='ブランチを保持する'),
        ),
    ]
