# Generated by Django 6.0.2 on 2026-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todo_keep_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=0, help_text='優先度（数値が大きいほど優先度高）'),
        ),
    ]
