# Generated by Django 6.0.2 on 2026-02-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0010_todo_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="finished_at",
            field=models.DateTimeField(blank=True, help_text="実行完了時刻", null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="started_at",
            field=models.DateTimeField(blank=True, help_text="実行開始時刻", null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="timeout",
            field=models.IntegerField(default=900, help_text="タイムアウト秒数"),
        ),
    ]
