# Generated by Django 6.0.2 on 2026-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0011_todo_finished_at_todo_started_at_alter_todo_timeout"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="interrupted_files",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="中断時の変更ファイルリスト（stash保存前の状態）",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="stash_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="中断時のstash ID（resume時に使用）",
                max_length=100,
            ),
        ),
    ]
