# Generated by Django 6.0.2 on 2026-02-27 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_todo_interrupted_files_todo_stash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='親TodoList', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='todo.todolist'),
        ),
    ]
